# Generated by Django 3.2.5 on 2021-07-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='Car',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='alias',
            new_name='brand',
        ),
    ]
